=== gzsolt0001/catalog/content/artifact-catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ac="https://nav.gov.hu/schema/artifact-catalog/v1"
           targetNamespace="https://nav.gov.hu/schema/artifact-catalog/v1"
           xmlns="https://nav.gov.hu/schema/artifact-catalog/v1"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">


    <xs:simpleType name="formIdType">
        <xs:annotation>
            <xs:documentation>Az űrlap technikai azonosítója</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="2"/>
            <xs:maxLength value="50"/>
            <xs:pattern value="[A-Z0-9][A-Z0-9_\-]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="formNameType">
        <xs:annotation>
            <xs:documentation>Az űrlap megnevezése</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="350"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="versionStringType">
        <xs:annotation>
            <xs:documentation>Űrlapverzió azonosítója</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="30"/>
            <xs:pattern value="[0-9]+(\.[0-9]+)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dateTimeOrEmptyType">
        <xs:annotation>
            <xs:documentation>ISO 8601 dateTime érték vagy üres érték. Üres érték esetén az adott időhatár nincs megadva.</xs:documentation>
        </xs:annotation>
        <xs:union memberTypes="xs:dateTime">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="0"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <xs:element name="artifactCatalog" type="ac:artifactCatalogType">
        <xs:annotation>
            <xs:documentation>A katalógus gyökéreleme</xs:documentation>
        </xs:annotation>
        <xs:unique name="uniqueFormId">
            <xs:selector xpath="ac:formsInformation/ac:form"/>
            <xs:field xpath="ac:formId"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="artifactCatalogType">
        <xs:sequence>
            <xs:element name="baseInformation" type="ac:baseInformationType">
                <xs:annotation>
                    <xs:documentation>A katalógus fejlécadatai</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="formsInformation" type="ac:formsInformationType">
                <xs:annotation>
                    <xs:documentation>A katalógusban nyilvántartott űrlaptípusok listája</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="baseInformationType">
        <xs:sequence>
            <xs:element name="catalogSchemaVersion" type="ac:versionStringType">
                <xs:annotation>
                    <xs:documentation>A séma verziója</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="generatedAt" type="xs:dateTime">
                <xs:annotation>
                    <xs:documentation>A katalógus generálásának időpontja ISO 8601 formátumban, Europe/Budapest időzóna szerinti dinamikus offsettel (+01:00/+02:00)</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="formsInformationType">
        <xs:sequence>
            <xs:element name="form" type="ac:formType" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Egy űrlap adatai</xs:documentation>
                </xs:annotation>
                <xs:unique name="uniqueFormVersionPerForm">
                    <xs:selector xpath="ac:versions/ac:version"/>
                    <xs:field xpath="ac:formVersion"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="formType">
        <xs:sequence>
            <xs:element name="formId" type="ac:formIdType">
                <xs:annotation>
                    <xs:documentation>Az űrlap technikai azonosítója</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="formName" type="ac:formNameType">
                <xs:annotation>
                    <xs:documentation>Az űrlap megnevezése</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="versions" type="ac:versionsType">
                <xs:annotation>
                    <xs:documentation>Az adott űrlaptípushoz tartozó űrlapverziók listája</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="versionsType">
        <xs:sequence>
            <xs:element name="version" type="ac:versionType" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Egy adott űrlaptípus verzió adatai</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="versionType">
        <xs:sequence>
            <xs:element name="formVersion" type="ac:versionStringType">
                <xs:annotation>
                    <xs:documentation>Űrlapverzió azonosító</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="validFrom" type="ac:dateTimeOrEmptyType" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Az űrlapverzió érvényességének kezdete ISO 8601 formátumban, Europe/Budapest időzóna szerinti dinamikus offsettel (+01:00/+02:00). Az időhatár inkluzív.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="validTo" type="ac:dateTimeOrEmptyType" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Az űrlapverzió érvényességének vége ISO 8601 formátumban, Europe/Budapest időzóna szerinti dinamikus offsettel (+01:00/+02:00). Az időhatár exkluzív.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="disabled" type="xs:boolean">
                <xs:annotation>
                    <xs:documentation>Tiltási jelző. true érték esetén az adott űrlapverzió nem tekinthető beadhatónak.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== gzsolt0001/catalog/content/artifact-catalog.xml
<?xml version='1.0' encoding='UTF-8'?>
<artifactCatalog xmlns="https://nav.gov.hu/schema/artifact-catalog/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://nav.gov.hu/schema/artifact-catalog/v1 artifact-catalog.xsd">
  <baseInformation>
    <catalogSchemaVersion>1.0</catalogSchemaVersion>
    <generatedAt>2026-09-21T15:07:00+02:00</generatedAt>
  </baseInformation>
  <formsInformation>
    <form>
      <formId>24GLBADO</formId>
      <formName>Bevallás a 2024. évi globális minimumadó-szintet biztosító kiegészítő adóról és az elismert belföldi</formName>
      <versions>
        <version>
          <formVersion>6.0</formVersion>
          <validFrom>2025-10-02T00:00:00+02:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
        <version>
          <formVersion>8.0</formVersion>
          <validFrom>2025-10-02T00:00:00+02:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2541</formId>
      <formName>Bevallás a társasházak részére a 2025. évi személyi jövedelemadóról</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2025-12-05T00:00:00+01:00</validFrom>
          <validTo>2026-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2601</formId>
      <formName>Bevallás az egyes adókötelezettségekről az államháztartással szemben</formName>
      <versions>
        <version>
          <formVersion>3.0</formVersion>
          <validFrom>2025-09-23T00:00:00+02:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2608INT</formId>
      <formName>Havi bevallás a 2019. évi CXXII. Törvény 87. § szerint kötelezettek részére a szociális hozzájárulási adóról</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2026-06-24T00:00:00+02:00</validFrom>
          <validTo></validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2611</formId>
      <formName>Bevallás az államháztartással szembeni egyes juttatások igényléséről</formName>
      <versions>
        <version>
          <formVersion>3.0</formVersion>
          <validFrom>2025-11-20T00:00:00+01:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>26110</formId>
      <formName>Igénylőlap az államháztartással szembeni gyakorított, illetve egyszeri támogatási előleg igényléséhez</formName>
      <versions>
        <version>
          <formVersion>3.0</formVersion>
          <validFrom>2025-11-17T00:00:00+01:00</validFrom>
          <validTo>2027-01-20T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2620</formId>
      <formName>Bevallás a biztosítási adóról, a biztosítási pótadóelőlegről, a biztosítási pótadó-elszámolásról</formName>
      <versions>
        <version>
          <formVersion>2.0</formVersion>
          <validFrom>2025-11-18T00:00:00+01:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>26251</formId>
      <formName>Bevallás a társasági adóelőlegről az átalakulással létrejött adóalanyok részére</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2024-10-18T00:00:00+02:00</validFrom>
          <validTo>2028-06-30T00:00:00+02:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2643TAO</formId>
      <formName>2643TAO</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom></validFrom>
          <validTo></validTo>
          <disabled>true</disabled>
        </version>
        <version>
          <formVersion>1.1</formVersion>
          <validFrom></validFrom>
          <validTo></validTo>
          <disabled>true</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2649</formId>
      <formName>Bevallás a 2025. évben kötelezetté váló adózók innovációs járulékelőlegéről</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2025-11-20T00:00:00+01:00</validFrom>
          <validTo>2028-07-20T00:00:00+02:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2650</formId>
      <formName>Bevallás a környezetterhelési díjelőlegről, illetve az éves díjkötelezettségről</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2025-11-26T00:00:00+01:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2651</formId>
      <formName>Bevallás a biztonságos és gazdaságos gyógyszer- és gyógyászatisegédeszköz-ellátás, valamint a gyógyszerforgalmazás</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2025-11-14T00:00:00+01:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2658</formId>
      <formName>Bevallás a kiegészítő tevékenységet folytatónak nem minősülő egyéni vállalkozó szociális hozzájárulási adó és járulék kö</formName>
      <versions>
        <version>
          <formVersion>2.0</formVersion>
          <validFrom>2025-12-05T00:00:00+01:00</validFrom>
          <validTo></validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2678</formId>
      <formName>Bevallás játékadóról</formName>
      <versions>
        <version>
          <formVersion>2.0</formVersion>
          <validFrom>2024-11-24T00:00:00+01:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2691</formId>
      <formName>Bevallás a távközlési szolgáltatást nyújtók távközlési adójáról</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2025-09-25T00:00:00+02:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>2693</formId>
      <formName>2693</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom></validFrom>
          <validTo></validTo>
          <disabled>true</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>26A215</formId>
      <formName>Negyedéves/Éves bevallás a szociálpolitikai menetdíj-támogatás személyszállítási tevékenységek szerinti adatairól</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2025-11-17T00:00:00+01:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>26A60</formId>
      <formName>26A60</formName>
      <versions>
        <version>
          <formVersion>2.0</formVersion>
          <validFrom></validFrom>
          <validTo></validTo>
          <disabled>true</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>26ENKADO</formId>
      <formName>Bevallás az energiaellátók különadó kötelezettségéről</formName>
      <versions>
        <version>
          <formVersion>3.0</formVersion>
          <validFrom>2026-02-19T00:00:00+01:00</validFrom>
          <validTo>2031-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>26HIPAK</formId>
      <formName>Bevallás a helyi iparűzési adóról állandó jellegű iparűzési tevékenység esetén</formName>
      <versions>
        <version>
          <formVersion>5.0</formVersion>
          <validFrom>2025-12-01T00:00:00+01:00</validFrom>
          <validTo>2033-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>26KATA</formId>
      <formName>Nyilatkozat és bevallás kisadózók részére a 2025. évre</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2025-11-24T00:00:00+01:00</validFrom>
          <validTo>2032-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>26KISKER</formId>
      <formName>Bevallás a kiskereskedelmi adóról és adóelőlegről</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
          <validFrom>2025-12-20T00:00:00+01:00</validFrom>
          <validTo>2033-12-31T00:00:00+01:00</validTo>
          <disabled>false</disabled>
        </version>
      </versions>
    </form>
    <form>
      <formId>26KIVA</formId>
      <formName>Bevallás a kisvállalati adóról és egyéb kötelezettségekről (társasági adó, innovációs járulék, energiaellátók jövedelema</formName>
      <versions>
        <version>
          <formVersion>1.0</formVersion>
